name: Martiallog
options:
  bundleIdPrefix: com.shimondeitel.martiallog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Martiallog:
    type: application
    platform: iOS
    sources:
      - path: Martiallog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.martiallog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Martiallog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  MartiallogTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MartiallogTests
      - path: Martiallog.storekit
    dependencies:
      - target: Martiallog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.martiallog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  MartiallogUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: MartiallogUITests
    dependencies:
      - target: Martiallog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.martiallog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Martiallog:
    build:
      targets:
        Martiallog: all
        MartiallogTests: [test]
        MartiallogUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Martiallog.storekit
    test:
      config: Debug
      storeKitConfiguration: Martiallog.storekit
      targets:
        - MartiallogTests
        - MartiallogUITests
    archive:
      config: Release
